
== Java Development Kit (JDK)
We're going to be writing our mods in Java...  so we need the Java Development Kit.  We're using JDK 8, which we downloaded from Oracle.
 You'll get your first exposure to 'license agreements'.  Go ahead and accept the license agreement - for projects you sell or share with others, you may need to pay more attention to license agreements overall.

Hmmm...  installing Java takes a while...  doot to doot to doot....
Make sure to set your JAVA_HOME environment variable...

== Downloading Forge
- Grab version which corresponds to server version of Minecraft
- Pay attention to the directions for download - don't get pulled into downloading something you didn't intend
- Pull down the source bundle, _not_ the installer.  The installer is good for running other people's mods.  But we're going to write our own!

== Building Forge
Didja know we were going to build software _before_ we wrote our software?

On Windows:
  `gradlew setupDecompWorkspace eclipse`

Watch lots of things scroll past...
... things are getting downloaded
... things are getting built
All of this is from the instructions put in the forge-...-src directory.

Doot to doot to doot...  OK, this is taking a while. (20 min 22.424 sec, eventually)  For the purposes of WIC day, we'll have set you up ahead using [TODO: vm?  vagrant script?  zip of completed?]
... build successful
